# Generated by Django 5.0.6 on 2024-06-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='name',
        ),
    ]
