# Generated by Django 4.2.8 on 2024-06-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_hitcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hitcount',
        ),
        migrations.AddField(
            model_name='tour',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
