# Generated by Django 4.2.8 on 2024-06-23 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gittour_alter_tour_guide_delete_git'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GitTour',
        ),
    ]
