# Generated by Django 4.2.8 on 2024-06-23 04:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_profileuser_is_guide_profileuser_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileUser',
            new_name='Git',
        ),
    ]
