# Generated by Django 4.2.8 on 2024-06-23 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_profileuser_delete_git_alter_tour_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to=settings.AUTH_USER_MODEL),
        ),
    ]
