# Generated by Django 4.2.8 on 2024-06-23 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_tour_guide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='guide',
            new_name='owner',
        ),
    ]
